### PR TITLE
Theming fixes

### PR DESCRIPTION
**Pull request by sak96**
- fix css theme issue with llight and dark themes.
- avoid doing fancy stuff use css attributes

### CODE REVIEW

**Comment by sak96** [comment]
@emanuele-em can you update the screenshots for this branch.
i use window manager which logs very different from normal view.

**Comment by sak96** [comment]
@emanuele-em  gentle reminder :stuck_out_tongue:

image

**Comment by emanuele-em** [comment]
@sak96 I am traveling now, I will be back available on April 5, I have made significant changes to the interface, on April 5 I will merge everything

**Comment by sak96** [comment]
remainder

**Comment by sak96** [comment]
@emanuele-emdid you manage to get time to push the change you made ?

**Comment by sak96** [comment]
? @emanuele-em was there any mistake in the pr ?

**Pull request closed without merging**
