### PR TITLE
Add Tauri Select row

### PR DESCRIPTION
**Pull request by sak96**
- show tab view when row is selcted/clicked

image

image

### CODE REVIEW

**Comment by sak96** [comment]
can be merged

**Comment by emanuele-em** [comment]
There are some error in b tauri-ui, there isn't a `header`, should maybe better to remove mitm_proxy and replace it totally, currently I can't run the new version

**Comment by sak96** [comment]
can you paste the error ?

**Comment by emanuele-em** [comment]
https://github.com/emanuele-em/man-in-the-middle-proxy/blob/tauri-yew-migration/tauri-ui/src/components/request/mod.rs

ok, I'll try today

**Comment by emanuele-em** [comment]
image

I see this on application run, I run by `cargo run` command from `tauri-ui` directory, it's right?

**Comment by sak96** [comment]
there is CONTRIBUTING.md  in tauri-ui folder

**Pull request merged**
